// Types for regime model API responses.
// Mirrors JSONB shapes from ix/db/models/regime_snapshot.py

// ── List models ─────────────────────────────────────────────────────

export type RegimeCategory = 'axis' | 'phase' | 'composite';

export interface RegimeModel {
  key: string;
  display_name: string;
  description: string;
  states: string[];
  dimensions: string[];
  has_strategy: boolean;
  category?: RegimeCategory;
  phase_pair?: string | null;
  color_map: Record<string, string>;
  dimension_colors: Record<string, string>;
  state_descriptions?: Record<string, string>;
  default_params: Record<string, unknown>;
  /** Universal quality snapshot. Populated when quality_snapshot.json
   *  has been generated by `scripts/quality_snapshot_regimes.py`. */
  quality?: QualitySnapshot | null;
  /** Forward-looking validation at designed horizon. Populated from
   *  quality_snapshot_v2.json by `scripts/validate_regimes.py`. */
  forward?: ForwardValidation | null;
}

export type RegimeTier = 'tier1' | 'tier2' | 'sensitive' | 'weak' | 'draft';

/** Forward-looking verdict from scripts/validate_regimes.py (v2). */
export type RegimeVerdict = 'STRONG' | 'PASS' | 'WEAK' | 'FAIL' | 'NOT_RUN';

/** Forward-looking validation metrics at the regime's designed horizon.
 *  Populated from quality_snapshot_v2.json. */
export interface ForwardValidation {
  verdict: RegimeVerdict;
  target: string;
  horizon_months: number;
  n_observations: number;

  // IC
  ic_spearman: number | null;
  ic_pvalue: number | null;
  /** Multi-horizon IC: {1: ic_1m, 3: ic_3m, 6: ic_6m, 12: ic_12m} */
  ic_curve: Record<string, number>;
  /** Horizon (months) where |IC| peaks */
  ic_peak_horizon: number | null;

  // Spread at designed horizon
  spread_ann: number | null;
  vol_normalized_spread: number | null;
  cohens_d: number | null;
  welch_p: number | null;
  best_state: string | null;
  worst_state: string | null;

  // Per-state stats
  per_state: Record<string, {
    mean_ann: number | null;
    vol_ann: number | null;
    sharpe: number | null;
    n: number;
  }>;

  // Lead time
  drawdown_events: number;
  hit_rate: number | null;
  lead_months_median: number | null;

  // Drawdown avoidance
  bh_max_dd: number | null;
  good_state_max_dd: number | null;
  bad_state_max_dd: number | null;
  dd_avoidance_pct: number | null;

  // OOS decay
  ic_pre2010: number | null;
  ic_post2010: number | null;
  spread_pre2010: number | null;
  spread_post2010: number | null;
  oos_sign_consistent: boolean | null;
  /** Post/pre spread ratio. 1.0=stable, 0.1=90% collapsed, >1=strengthened */
  oos_spread_decay: number | null;

  // Transition quality
  n_transitions: number;
  false_positive_rate: number | null;

  issues: string[];
}

export interface QualityOverlap {
  key: string;
  rho: number;
  n: number;
}

export interface QualitySnapshot {
  target: string;
  horizon_months: number;
  n_observations: number;
  n_states: number;
  tier: RegimeTier;
  tier_rationale: string;
  phase_pair?: string | null;
  phase_pair_waiver_applied: boolean;

  // Tier 1 raw metrics
  coverage: number | null;
  median_run_months: number | null;
  min_state_n: number | null;
  spread_ann: number | null;
  vol_normalized_spread: number | null;
  welch_p: number | null;
  subsample_sign_consistent: boolean | null;
  sensitivity_verdict: string | null;
  state_balance_verdict: string | null;
  state_balance_entropy: number | null;

  // Tier 1 pass flags
  t11_coverage_pass: boolean | null;
  t12_run_length_pass: boolean | null;
  t13_min_n_pass: boolean | null;
  t14_volnorm_pass: boolean | null;
  t15_welch_pass: boolean | null;
  t16_subsample_pass: boolean | null;
  t17_sensitivity_pass: boolean | null;
  t18_balance_pass: boolean | null;

  // Sensitivity grid stats
  grid_default_spread: number | null;
  grid_median_spread: number | null;
  grid_min_spread: number | null;
  grid_max_spread: number | null;
  grid_fragile_cells: number | null;
  grid_sign_flips: number | null;

  // Diagnostics
  error?: string | null;
  overlaps: QualityOverlap[];
}

/** Compose endpoint response — same shape as a normal regime snapshot
 * but bundled together (current + timeseries + assets + meta + model). */
export interface ComposeResponse {
  model: RegimeModel;
  current_state: CurrentState;
  timeseries: TimeseriesData;
  asset_analytics: AssetAnalytics | null;
  meta: MetaData;
  strategy: StrategyData | null;
}

export interface ModelsResponse {
  models: RegimeModel[];
}

// ── Current state ───────────────────────────────────────────────────

export interface DimensionData {
  z: number;
  p: number;
  direction: string;
  score: number;
  total: number;
  components: { name: string; z: number }[];
  /** Trailing 24-month z-score history for sparkline rendering. */
  history?: number[];
  /** 3-month z acceleration (z[-1] - z[-3]) for cycle direction. */
  acceleration?: number | null;
}

export interface MarketSignal {
  name: string;
  value: string;
  aligned: boolean | null;
}

export interface MarketConfirmation {
  verdict: string;
  score: number;
  total: number;
  signals: MarketSignal[];
}

/** Historical context for the current joint state — populated by the
 * compose endpoint to power the Regime Profile panel. */
export interface RegimeStats {
  occurrences: number;          // # of distinct historical episodes
  months_in_state: number;      // total months ever in this state
  total_months: number;         // total months of composite history
  frequency_pct: number;        // months_in_state / total_months × 100
  avg_run_months: number;       // avg episode length when this state appears
  current_run_months: number;   // current consecutive run
  best_asset: AssetSnippet | null;
  worst_asset: AssetSnippet | null;
  top_separation: {
    ticker: string;
    cohens_d: number | null;
    p_value: number | null;
    best_state: string | null;
    worst_state: string | null;
  } | null;
}

export interface AssetSnippet {
  ticker: string;
  ann_ret: number | null;
  sharpe: number | null;
  win_rate: number | null;
  max_dd?: number | null;
}

/** Per-input-regime current state aligned to the joint composite's date.
 * Populated by the compose endpoint so AxisDock can show consistent
 * values for regimes that are part of the active composition. */
export interface InputRegimeState {
  dominant: string;
  dominant_probability: number;
  months_in_regime: number;
  date: string;
  conviction: number;
  z_history?: number[];
  z_acceleration?: number | null;
}

/** Single PM-actionable read produced by compose.py. Wraps the verdict,
 * the assets to tilt toward/away from, the four DC gates, and the watch
 * list of input axes likely to flip per the 12M Markov. */
export interface DecisionCard {
  verdict: 'RISK-ON' | 'RISK-OFF' | 'MIXED' | 'NEUTRAL';
  primary_ticker: string | null;
  tilt_long: string[];
  tilt_short: string[];
  gates: {
    dc1_separation: boolean;
    dc2_persistence: boolean;
    dc3_conviction: boolean;
    dc4_sample_size: boolean;
  };
  watch: { axis: string; from: string; to: string }[];
}

export interface CurrentState {
  date: string | null;
  dominant: string;
  dominant_probability: number;
  conviction: number;
  months_in_regime: number;
  transitioning?: boolean;
  tactical_regime?: string;
  strategic_regime?: string;
  probabilities: Record<string, number>;
  forward_probabilities?: Record<string, number>;
  /** Multi-horizon Markov projections keyed by month count.
   * Backend serializes integer keys as strings ("1", "3", "6", "12"). */
  forward_horizons?: Record<string, Record<string, number>>;
  decision_card?: DecisionCard | null;
  input_states?: Record<string, InputRegimeState>;
  acceleration?: { growth: number | null; inflation: number | null };
  momentum_3m?: { growth: number | null; inflation: number | null; implied_regime: string | null };
  dimensions: Record<string, DimensionData>;
  current_allocation?: {
    macro_regime: string;
    liquidity_regime: string;
    weights: Record<string, number>;
  };
  blended_allocation?: Record<string, number>;
  liquidity_scaling?: { status: string; scale_factor_pct: number };
  nowcast?: { claims_4wma_z: number | null; model_growth_z: number | null };
  market_confirmation?: MarketConfirmation;
  recent_probabilities?: { dates: string[]; [regime: string]: number[] | string[] };
  regime_stats?: RegimeStats;
  error?: string;
}

export interface CurrentStateResponse {
  regime_type: string;
  computed_at: string;
  parameters: Record<string, unknown>;
  current_state: CurrentState;
}

// ── Timeseries ──────────────────────────────────────────────────────

export interface CorrelationMatrix {
  names: string[];
  matrix: number[][];
}

export interface TransitionRow {
  date: string;
  regime: string;
  probability: string;
}

export interface TimeseriesData {
  dates: string[];
  composites: Record<string, (number | null)[]>;
  /** Raw sigmoid probabilities (P_{state}) — pre-EMA. */
  raw_probabilities?: Record<string, (number | null)[]>;
  /** @deprecated Legacy alias for raw_probabilities. Kept for backward
   *  compatibility with old cached snapshots. */
  probabilities: Record<string, (number | null)[]>;
  /** Smoothed probabilities (S_P_{state}) — post-EMA. Matches the
   *  `dominant_probability` in the /current endpoint. Use this for
   *  any display that should be consistent with the current state card. */
  smoothed_probabilities: Record<string, (number | null)[]>;
  dominant: string[];
  conviction: (number | null)[];
  indicators: Record<string, (number | null)[]>;
  correlations?: Record<string, CorrelationMatrix>;
  transitions_recent?: TransitionRow[];
  transition_matrix?: Record<string, Record<string, number>>;
  durations?: Record<string, { avg_months: number; episodes: number }>;
}

export interface TimeseriesResponse {
  regime_type: string;
  computed_at: string;
  timeseries: TimeseriesData;
}

// ── Strategy ────────────────────────────────────────────────────────

export interface StrategyStats {
  cagr: number;
  ann_vol: number;
  sharpe: number;
  max_dd: number;
  months: number;
}

export interface StrategyModel {
  label: string;
  description: string;
  dates: string[];
  equity: number[];
  drawdown: number[];
  stats: StrategyStats;
}

export interface YearlyReturn {
  year: number;
  wf_best: number;
  diversified: number;
  spy: number;
  wf_alpha: number;
  div_alpha: number;
}

export interface HoldingsHistory {
  dates: string[];
  holdings: Record<string, number>[];
}

export interface StrategyData {
  start_date: string | null;
  end_date: string | null;
  months: number;
  wf_lookback: number;
  num_assets: number;
  lag_months: number;
  models: Record<string, StrategyModel>;
  regime_history: { dates: string[]; regimes: string[] };
  yearly_returns: YearlyReturn[];
  allocation_templates: Record<string, Record<string, number>>;
  assets: string[];
  holdings_history?: HoldingsHistory;
  cost_bps?: number;
}

export interface StrategyResponse {
  regime_type: string;
  computed_at: string;
  strategy: StrategyData;
}

// ── Ensemble ───────────────────────────────────────────────────────

export interface EnsembleDriver {
  regime: string;
  ic: number;
  ic_pvalue: number;
  z_current: number;
}

export interface EnsembleMeta {
  total_regimes: number;
  regime_keys: string[];
  horizon_months: number;
  significance_threshold: number;
  warmup_months: number;
}

export interface EnsembleResponse extends StrategyData {
  ensemble_meta: EnsembleMeta;
  current_weights: Record<string, number>;
  regime_drivers: Record<string, EnsembleDriver[]>;
}

// ── Asset analytics ─────────────────────────────────────────────────

export interface AssetStat {
  ticker: string;
  ann_ret: number | null;
  ann_vol: number | null;
  sharpe: number | null;
  win_rate: number | null;
  max_dd: number | null;
  worst_mo: number | null;
  best_mo: number | null;
  months: number;
}

export interface RegimeAssetStats {
  months: number;
  assets: AssetStat[];
}

export interface LiquiditySplitBucket {
  label: string;
  description: string;
  months: number;
  assets: { ticker: string; ann_ret: number | null; sharpe: number | null; months: number }[];
}

export interface LiquiditySplit {
  supportive: LiquiditySplitBucket;
  stressed: LiquiditySplitBucket;
}

export interface RegimeSeparation {
  cohens_d: number | null;       // standardized mean diff: (best - worst) / pooled_std
  p_value: number | null;        // Welch t-test p-value for best vs worst
  best_state: string | null;
  worst_state: string | null;
  eta_sq: number | null;         // ANOVA η² across all states (reference)
  n: number;
}

/** Spearman IC between the regime's composite Z-score and an asset's
 *  forward return at the regime's designed horizon. */
export interface AssetIC {
  ic: number | null;
  ic_pvalue: number | null;
  n: number;
  horizon: number;
}

export interface AssetAnalytics {
  per_regime_stats: Record<string, RegimeAssetStats>;
  regime_counts: Record<string, { months: number; pct: number }>;
  expected_returns: Record<string, number>;
  small_sample_regimes: string[];
  regime_separation?: Record<string, RegimeSeparation>;
  /** Per-asset Spearman IC at the regime's designed horizon.
   *  Null/absent for composites (no single Z-score signal). */
  signal_ic?: Record<string, AssetIC> | null;
  liquidity_splits: Record<string, LiquiditySplit>;
  tickers: string[];
}

export interface AssetAnalyticsResponse {
  regime_type: string;
  computed_at: string;
  asset_analytics: AssetAnalytics;
}

// ── Meta ────────────────────────────────────────────────────────────

export interface IndicatorDoc {
  name: string;
  code: string;
  lag: number;
  type: string;
  rationale: string;
}

export interface DimensionDoc {
  description: string;
  indicators: IndicatorDoc[];
}

export interface MetaData {
  model_name: string;
  description: string;
  states: string[];
  dimensions: string[];
  color_map: Record<string, string>;
  dimension_colors: Record<string, string>;
  methodology: Record<string, string>;
  indicator_docs?: Record<string, DimensionDoc>;
  regime_definitions?: Record<string, { growth?: string; inflation?: string; description: string }>;
}

export interface MetaResponse {
  regime_type: string;
  computed_at: string;
  meta: MetaData;
}

// ── Tab type ────────────────────────────────────────────────────────

export type RegimeTab =
  | 'current'
  | 'history'
  | 'indicators'
  | 'assets'
  | 'playbook'
  | 'strategy'
  | 'model';
