"""Create whiteboards for all users who don't have any."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from ix.db.conn import Session
from ix.db.models import Whiteboard, User

template_thesis = {
    "elements": [
        {"id": "tmpl_title", "type": "text", "x": 100, "y": 50, "width": 600, "height": 36,
         "strokeColor": "#1e1e1e", "backgroundColor": "transparent",
         "text": "Investment Thesis Framework", "fontSize": 28, "fontFamily": 1,
         "textAlign": "center", "verticalAlign": "top", "containerId": None,
         "originalText": "Investment Thesis Framework", "autoResize": True, "lineHeight": 1.25,
         "fillStyle": "hachure", "strokeWidth": 2, "strokeStyle": "solid", "roughness": 1,
         "opacity": 100, "angle": 0, "isDeleted": False, "groupIds": [], "frameId": None,
         "index": None, "link": None, "locked": False, "version": 1, "versionNonce": 1,
         "seed": 12345, "roundness": None, "boundElements": None},
        {"id": "box_macro", "type": "rectangle", "x": 100, "y": 120, "width": 220, "height": 150,
         "strokeColor": "#1971c2", "backgroundColor": "#a5d8ff",
         "fillStyle": "hachure", "strokeWidth": 2, "strokeStyle": "solid", "roughness": 1,
         "opacity": 100, "angle": 0, "isDeleted": False, "groupIds": [], "frameId": None,
         "index": None, "link": None, "locked": False, "version": 1, "versionNonce": 1,
         "seed": 22345, "roundness": {"type": 3},
         "boundElements": [{"id": "txt_macro", "type": "text"}]},
        {"id": "txt_macro", "type": "text", "x": 100, "y": 120, "width": 220, "height": 150,
         "strokeColor": "#1e1e1e", "backgroundColor": "transparent",
         "text": "MACRO OUTLOOK\n\n\u2022 GDP / CPI\n\u2022 Fed Policy\n\u2022 Credit Spreads",
         "fontSize": 16, "fontFamily": 1, "textAlign": "center", "verticalAlign": "middle",
         "containerId": "box_macro",
         "originalText": "MACRO OUTLOOK\n\n\u2022 GDP / CPI\n\u2022 Fed Policy\n\u2022 Credit Spreads",
         "autoResize": True, "lineHeight": 1.25,
         "fillStyle": "hachure", "strokeWidth": 2, "strokeStyle": "solid", "roughness": 1,
         "opacity": 100, "angle": 0, "isDeleted": False, "groupIds": [], "frameId": None,
         "index": None, "link": None, "locked": False, "version": 1, "versionNonce": 1,
         "seed": 32345, "roundness": None, "boundElements": None},
        {"id": "box_signals", "type": "rectangle", "x": 400, "y": 120, "width": 220, "height": 150,
         "strokeColor": "#2f9e44", "backgroundColor": "#b2f2bb",
         "fillStyle": "hachure", "strokeWidth": 2, "strokeStyle": "solid", "roughness": 1,
         "opacity": 100, "angle": 0, "isDeleted": False, "groupIds": [], "frameId": None,
         "index": None, "link": None, "locked": False, "version": 1, "versionNonce": 1,
         "seed": 42345, "roundness": {"type": 3},
         "boundElements": [{"id": "txt_signals", "type": "text"}]},
        {"id": "txt_signals", "type": "text", "x": 400, "y": 120, "width": 220, "height": 150,
         "strokeColor": "#1e1e1e", "backgroundColor": "transparent",
         "text": "SIGNALS\n\n\u2022 Trend (40w SMA)\n\u2022 Macro Composite\n\u2022 VIX Regime",
         "fontSize": 16, "fontFamily": 1, "textAlign": "center", "verticalAlign": "middle",
         "containerId": "box_signals",
         "originalText": "SIGNALS\n\n\u2022 Trend (40w SMA)\n\u2022 Macro Composite\n\u2022 VIX Regime",
         "autoResize": True, "lineHeight": 1.25,
         "fillStyle": "hachure", "strokeWidth": 2, "strokeStyle": "solid", "roughness": 1,
         "opacity": 100, "angle": 0, "isDeleted": False, "groupIds": [], "frameId": None,
         "index": None, "link": None, "locked": False, "version": 1, "versionNonce": 1,
         "seed": 52345, "roundness": None, "boundElements": None},
        {"id": "box_alloc", "type": "rectangle", "x": 700, "y": 120, "width": 220, "height": 150,
         "strokeColor": "#e8590c", "backgroundColor": "#ffd8a8",
         "fillStyle": "hachure", "strokeWidth": 2, "strokeStyle": "solid", "roughness": 1,
         "opacity": 100, "angle": 0, "isDeleted": False, "groupIds": [], "frameId": None,
         "index": None, "link": None, "locked": False, "version": 1, "versionNonce": 1,
         "seed": 62345, "roundness": {"type": 3},
         "boundElements": [{"id": "txt_alloc", "type": "text"}]},
        {"id": "txt_alloc", "type": "text", "x": 700, "y": 120, "width": 220, "height": 150,
         "strokeColor": "#1e1e1e", "backgroundColor": "transparent",
         "text": "ALLOCATION\n\n90% Risk-On\n50% Neutral\n10% Risk-Off",
         "fontSize": 16, "fontFamily": 1, "textAlign": "center", "verticalAlign": "middle",
         "containerId": "box_alloc",
         "originalText": "ALLOCATION\n\n90% Risk-On\n50% Neutral\n10% Risk-Off",
         "autoResize": True, "lineHeight": 1.25,
         "fillStyle": "hachure", "strokeWidth": 2, "strokeStyle": "solid", "roughness": 1,
         "opacity": 100, "angle": 0, "isDeleted": False, "groupIds": [], "frameId": None,
         "index": None, "link": None, "locked": False, "version": 1, "versionNonce": 1,
         "seed": 72345, "roundness": None, "boundElements": None},
        {"id": "arr_1", "type": "arrow", "x": 320, "y": 195, "width": 80, "height": 0,
         "strokeColor": "#1e1e1e", "backgroundColor": "transparent",
         "points": [[0, 0], [80, 0]],
         "fillStyle": "hachure", "strokeWidth": 2, "strokeStyle": "solid", "roughness": 1,
         "opacity": 100, "angle": 0, "isDeleted": False, "groupIds": [], "frameId": None,
         "index": None, "link": None, "locked": False, "version": 1, "versionNonce": 1,
         "seed": 12346, "roundness": {"type": 2}, "boundElements": None,
         "startBinding": {"elementId": "box_macro", "focus": 0, "gap": 8, "fixedPoint": None},
         "endBinding": {"elementId": "box_signals", "focus": 0, "gap": 8, "fixedPoint": None},
         "startArrowhead": None, "endArrowhead": "arrow", "elbowed": False},
        {"id": "arr_2", "type": "arrow", "x": 620, "y": 195, "width": 80, "height": 0,
         "strokeColor": "#1e1e1e", "backgroundColor": "transparent",
         "points": [[0, 0], [80, 0]],
         "fillStyle": "hachure", "strokeWidth": 2, "strokeStyle": "solid", "roughness": 1,
         "opacity": 100, "angle": 0, "isDeleted": False, "groupIds": [], "frameId": None,
         "index": None, "link": None, "locked": False, "version": 1, "versionNonce": 1,
         "seed": 22346, "roundness": {"type": 2}, "boundElements": None,
         "startBinding": {"elementId": "box_signals", "focus": 0, "gap": 8, "fixedPoint": None},
         "endBinding": {"elementId": "box_alloc", "focus": 0, "gap": 8, "fixedPoint": None},
         "startArrowhead": None, "endArrowhead": "arrow", "elbowed": False},
    ],
    "appState": {"viewBackgroundColor": "#ffffff", "gridSize": None},
    "files": {}
}

template_regime = {
    "elements": [
        {"id": "reg_title", "type": "text", "x": 80, "y": 30, "width": 700, "height": 40,
         "strokeColor": "#1e1e1e", "backgroundColor": "transparent",
         "text": "Market Regime Dashboard", "fontSize": 32, "fontFamily": 1,
         "textAlign": "left", "verticalAlign": "top", "containerId": None,
         "originalText": "Market Regime Dashboard", "autoResize": True, "lineHeight": 1.25,
         "fillStyle": "hachure", "strokeWidth": 2, "strokeStyle": "solid", "roughness": 0,
         "opacity": 100, "angle": 0, "isDeleted": False, "groupIds": [], "frameId": None,
         "index": None, "link": None, "locked": False, "version": 1, "versionNonce": 1,
         "seed": 99001, "roundness": None, "boundElements": None},
        {"id": "box_risk_on", "type": "rectangle", "x": 80, "y": 100, "width": 200, "height": 120,
         "strokeColor": "#2f9e44", "backgroundColor": "#b2f2bb",
         "fillStyle": "solid", "strokeWidth": 2, "strokeStyle": "solid", "roughness": 0,
         "opacity": 100, "angle": 0, "isDeleted": False, "groupIds": [], "frameId": None,
         "index": None, "link": None, "locked": False, "version": 1, "versionNonce": 1,
         "seed": 99010, "roundness": {"type": 3},
         "boundElements": [{"id": "txt_risk_on", "type": "text"}]},
        {"id": "txt_risk_on", "type": "text", "x": 80, "y": 100, "width": 200, "height": 120,
         "strokeColor": "#1e1e1e", "backgroundColor": "transparent",
         "text": "RISK-ON\n90% Equity\n\nTrend UP + Macro UP",
         "fontSize": 16, "fontFamily": 1, "textAlign": "center", "verticalAlign": "middle",
         "containerId": "box_risk_on",
         "originalText": "RISK-ON\n90% Equity\n\nTrend UP + Macro UP",
         "autoResize": True, "lineHeight": 1.25,
         "fillStyle": "hachure", "strokeWidth": 2, "strokeStyle": "solid", "roughness": 0,
         "opacity": 100, "angle": 0, "isDeleted": False, "groupIds": [], "frameId": None,
         "index": None, "link": None, "locked": False, "version": 1, "versionNonce": 1,
         "seed": 99011, "roundness": None, "boundElements": None},
        {"id": "box_neutral", "type": "rectangle", "x": 330, "y": 100, "width": 200, "height": 120,
         "strokeColor": "#e8590c", "backgroundColor": "#ffd8a8",
         "fillStyle": "solid", "strokeWidth": 2, "strokeStyle": "solid", "roughness": 0,
         "opacity": 100, "angle": 0, "isDeleted": False, "groupIds": [], "frameId": None,
         "index": None, "link": None, "locked": False, "version": 1, "versionNonce": 1,
         "seed": 99020, "roundness": {"type": 3},
         "boundElements": [{"id": "txt_neutral", "type": "text"}]},
        {"id": "txt_neutral", "type": "text", "x": 330, "y": 100, "width": 200, "height": 120,
         "strokeColor": "#1e1e1e", "backgroundColor": "transparent",
         "text": "NEUTRAL\n50% Equity\n\nMixed Signals",
         "fontSize": 16, "fontFamily": 1, "textAlign": "center", "verticalAlign": "middle",
         "containerId": "box_neutral",
         "originalText": "NEUTRAL\n50% Equity\n\nMixed Signals",
         "autoResize": True, "lineHeight": 1.25,
         "fillStyle": "hachure", "strokeWidth": 2, "strokeStyle": "solid", "roughness": 0,
         "opacity": 100, "angle": 0, "isDeleted": False, "groupIds": [], "frameId": None,
         "index": None, "link": None, "locked": False, "version": 1, "versionNonce": 1,
         "seed": 99021, "roundness": None, "boundElements": None},
        {"id": "box_risk_off", "type": "rectangle", "x": 580, "y": 100, "width": 200, "height": 120,
         "strokeColor": "#e03131", "backgroundColor": "#ffc9c9",
         "fillStyle": "solid", "strokeWidth": 2, "strokeStyle": "solid", "roughness": 0,
         "opacity": 100, "angle": 0, "isDeleted": False, "groupIds": [], "frameId": None,
         "index": None, "link": None, "locked": False, "version": 1, "versionNonce": 1,
         "seed": 99030, "roundness": {"type": 3},
         "boundElements": [{"id": "txt_risk_off", "type": "text"}]},
        {"id": "txt_risk_off", "type": "text", "x": 580, "y": 100, "width": 200, "height": 120,
         "strokeColor": "#1e1e1e", "backgroundColor": "transparent",
         "text": "RISK-OFF\n10% Equity\n\nTrend DN + Macro DN",
         "fontSize": 16, "fontFamily": 1, "textAlign": "center", "verticalAlign": "middle",
         "containerId": "box_risk_off",
         "originalText": "RISK-OFF\n10% Equity\n\nTrend DN + Macro DN",
         "autoResize": True, "lineHeight": 1.25,
         "fillStyle": "hachure", "strokeWidth": 2, "strokeStyle": "solid", "roughness": 0,
         "opacity": 100, "angle": 0, "isDeleted": False, "groupIds": [], "frameId": None,
         "index": None, "link": None, "locked": False, "version": 1, "versionNonce": 1,
         "seed": 99031, "roundness": None, "boundElements": None},
        {"id": "box_indicators", "type": "rectangle", "x": 80, "y": 280, "width": 350, "height": 160,
         "strokeColor": "#1971c2", "backgroundColor": "#a5d8ff",
         "fillStyle": "solid", "strokeWidth": 2, "strokeStyle": "solid", "roughness": 0,
         "opacity": 100, "angle": 0, "isDeleted": False, "groupIds": [], "frameId": None,
         "index": None, "link": None, "locked": False, "version": 1, "versionNonce": 1,
         "seed": 99050, "roundness": {"type": 3},
         "boundElements": [{"id": "txt_indicators", "type": "text"}]},
        {"id": "txt_indicators", "type": "text", "x": 80, "y": 280, "width": 350, "height": 160,
         "strokeColor": "#1e1e1e", "backgroundColor": "transparent",
         "text": "KEY INDICATORS (by IC)\n\n1. CESI Breadth (+0.247)\n2. HY/IG Ratio (-0.195)\n3. VIX (+0.157)\n4. Fed Net Liquidity (+0.148)\n5. OECD CLI EM (+0.143)",
         "fontSize": 16, "fontFamily": 1, "textAlign": "left", "verticalAlign": "middle",
         "containerId": "box_indicators",
         "originalText": "KEY INDICATORS (by IC)\n\n1. CESI Breadth (+0.247)\n2. HY/IG Ratio (-0.195)\n3. VIX (+0.157)\n4. Fed Net Liquidity (+0.148)\n5. OECD CLI EM (+0.143)",
         "autoResize": True, "lineHeight": 1.25,
         "fillStyle": "hachure", "strokeWidth": 2, "strokeStyle": "solid", "roughness": 0,
         "opacity": 100, "angle": 0, "isDeleted": False, "groupIds": [], "frameId": None,
         "index": None, "link": None, "locked": False, "version": 1, "versionNonce": 1,
         "seed": 99051, "roundness": None, "boundElements": None},
        {"id": "box_perf", "type": "rectangle", "x": 480, "y": 280, "width": 300, "height": 160,
         "strokeColor": "#7048e8", "backgroundColor": "#d0bfff",
         "fillStyle": "solid", "strokeWidth": 2, "strokeStyle": "solid", "roughness": 0,
         "opacity": 100, "angle": 0, "isDeleted": False, "groupIds": [], "frameId": None,
         "index": None, "link": None, "locked": False, "version": 1, "versionNonce": 1,
         "seed": 99060, "roundness": {"type": 3},
         "boundElements": [{"id": "txt_perf", "type": "text"}]},
        {"id": "txt_perf", "type": "text", "x": 480, "y": 280, "width": 300, "height": 160,
         "strokeColor": "#1e1e1e", "backgroundColor": "transparent",
         "text": "BACKTEST RESULTS\n\nAvg Sharpe: 0.57\nAvg Alpha: +3.4%/yr\nRolling IC+: 87%\n\nAll 9 indices positive alpha",
         "fontSize": 16, "fontFamily": 1, "textAlign": "left", "verticalAlign": "middle",
         "containerId": "box_perf",
         "originalText": "BACKTEST RESULTS\n\nAvg Sharpe: 0.57\nAvg Alpha: +3.4%/yr\nRolling IC+: 87%\n\nAll 9 indices positive alpha",
         "autoResize": True, "lineHeight": 1.25,
         "fillStyle": "hachure", "strokeWidth": 2, "strokeStyle": "solid", "roughness": 0,
         "opacity": 100, "angle": 0, "isDeleted": False, "groupIds": [], "frameId": None,
         "index": None, "link": None, "locked": False, "version": 1, "versionNonce": 1,
         "seed": 99061, "roundness": None, "boundElements": None},
    ],
    "appState": {"viewBackgroundColor": "#ffffff", "gridSize": None},
    "files": {}
}

with Session() as s:
    users = s.query(User).all()
    created = 0
    for user in users:
        existing = s.query(Whiteboard).filter(
            Whiteboard.user_id == str(user.id),
            Whiteboard.is_deleted == False
        ).count()
        if existing > 0:
            print(f"  User {user.email} already has {existing} whiteboards, skipping")
            continue
        wb1 = Whiteboard(user_id=str(user.id), title="Investment Thesis Framework", scene_data=template_thesis)
        wb2 = Whiteboard(user_id=str(user.id), title="Market Regime Dashboard", scene_data=template_regime)
        s.add(wb1)
        s.add(wb2)
        created += 2
        print(f"  Created 2 whiteboards for {user.email}")
    s.commit()
    print(f"\nDone! Created {created} whiteboards total")
